field: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
fieldLayouts:
  a0493dba-06c8-4dd6-ba71-c90579ce7c72:
    tabs:
      -
        elements:
          -
            fieldUid: c88dc31c-dfde-42c6-93df-6af9d0c907b8 # URL
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 728454ec-f7c5-4150-b280-3824ff557e01
            warning: null
            width: 100
        name: Content
        uid: 97892947-fde5-4846-8b20-a07b4c84206f
fields:
  c88dc31c-dfde-42c6-93df-6af9d0c907b8: # URL
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: embed
    instructions: 'Enter a URL link to Twitter tweet, Instagram post, YouTube video, and more.'
    name: URL
    searchable: false
    settings:
      errorMessage: 'Unable to find component class ''wrav\oembed\fields\OembedField''.'
      expectedType: wrav\oembed\fields\OembedField
      settings: '{"url":""}'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MissingField
handle: embed
name: 'Social Embed'
sortOrder: 9
