field: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
fieldLayouts:
  2e620162-c9b6-427b-8b34-01749ceed604:
    tabs:
      -
        elements:
          -
            fieldUid: e44383bb-8f5a-4b3b-9114-30a955feb64c # Form
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56148128-96bc-4a82-bd9e-79c2e3d0c819
            warning: null
            width: 100
          -
            fieldUid: a4c579fb-e9c9-4d0c-91f6-1b3d9980c5ee # Success Message
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b126236b-0d40-4260-bc17-a9e3bffa8b9e
            warning: null
            width: 100
        name: Content
        uid: 0c40cfb4-32d4-4f05-8813-99b00af4d589
fields:
  a4c579fb-e9c9-4d0c-91f6-1b3d9980c5ee: # Success Message
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: successMessage
    instructions: 'Optional success message for this specific form.'
    name: 'Success Message'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e44383bb-8f5a-4b3b-9114-30a955feb64c: # Form
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: form
    instructions: null
    name: Form
    searchable: true
    settings:
      errorMessage: 'Unable to find component class ''Solspace\Freeform\FieldTypes\FormFieldType''.'
      expectedType: Solspace\Freeform\FieldTypes\FormFieldType
      settings: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MissingField
handle: form
name: Form
sortOrder: 8
