field: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
fieldLayouts:
  e8d49680-7ba8-48aa-83b6-01f3ddbfe9c4:
    tabs:
      -
        elements:
          -
            fieldUid: 4e48185d-8e74-4fa1-b4b4-fdac5ceddf6d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09fd8132-5639-4a40-9e20-286d85d3b031
            warning: null
            width: 100
          -
            fieldUid: f668aa75-41bb-4309-9114-26d72e1547ff # CTA Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 279a182a-5491-4d0b-8fa5-9574c8cec914
            warning: null
            width: 100
          -
            fieldUid: b7672c12-833b-4554-afc9-ec3d68dbd78d # CTA Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d82a3af3-21ff-411a-ba0e-cb274e6ae98e
            warning: null
            width: 100
          -
            fieldUid: 11b555a2-89cb-434c-a97c-8bf858a76326 # Slide Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5425b8f2-a1aa-4706-9b8e-2a4c3462a4b3
            warning: null
            width: 100
          -
            fieldUid: 13b529cb-1236-4eb5-95a0-e20c2358385e # Slide Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fba6ff79-8b37-45fe-9b22-cec340091674
            warning: null
            width: 100
          -
            fieldUid: e6e6fbf0-a370-48de-b635-6f31bece3c9d # Slide Layout Centered
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d87841c-b748-4950-8f6b-b820557a4520
            warning: null
            width: 100
          -
            fieldUid: 85241ed2-6bbd-4dd0-af5c-07842116ccf3 # Dark UI
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce69f27e-93e6-46f4-a337-36a15cf3b3ec
            warning: null
            width: 100
        name: Content
        uid: 3c0a0d72-a79a-47de-adc1-9b60d82ca555
fields:
  4e48185d-8e74-4fa1-b4b4-fdac5ceddf6d: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  11b555a2-89cb-434c-a97c-8bf858a76326: # Slide Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: slideImages
    instructions: null
    name: 'Slide Images'
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  13b529cb-1236-4eb5-95a0-e20c2358385e: # Slide Entries
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: slideEntries
    instructions: null
    name: 'Slide Entries'
    searchable: true
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  85241ed2-6bbd-4dd0-af5c-07842116ccf3: # Dark UI
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: darkUI
    instructions: null
    name: 'Dark UI'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  b7672c12-833b-4554-afc9-ec3d68dbd78d: # CTA Link Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: ctaLinkText
    instructions: null
    name: 'CTA Link Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e6e6fbf0-a370-48de-b635-6f31bece3c9d: # Slide Layout Centered
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: slideLayoutCentered
    instructions: 'When enabled it''s best to have 6+ Slide Images/Entries so that the slider will wrap nicely on wide screens.'
    name: 'Slide Layout Centered'
    searchable: true
    settings:
      default: true
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  f668aa75-41bb-4309-9114-26d72e1547ff: # CTA Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: ctaLink
    instructions: null
    name: 'CTA Link'
    searchable: true
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: slider
name: Slider
sortOrder: 4
