field: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
fieldLayouts:
  b00121d3-e692-4fad-9a4d-14069ec52bf4:
    tabs:
      -
        elements:
          -
            fieldUid: d10684d5-bcd7-4e35-b0be-69377f981c39 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 242e0e5b-1a38-4ac1-9799-ec159f11b9ff
            warning: null
            width: 100
          -
            fieldUid: eb7b8bc9-c07a-4a25-9201-8174bd70fcb9 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 254c6308-6a4a-4c97-b455-92208117209d
            warning: null
            width: 100
          -
            fieldUid: 00f86307-b225-423b-bd34-b70af6632cf2 # Link Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3da2eb88-49f2-43f2-941e-784a89d520e9
            warning: null
            width: 100
          -
            fieldUid: f466ab59-2e29-4cce-85b8-f9ebe7000b03 # Internal Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a79c153-3215-4d4c-8d21-4de5707648a1
            warning: null
            width: 100
          -
            fieldUid: 52ff2568-6318-44d5-a130-818c19f83360 # External Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e664ea70-6eb4-4b59-855d-006785c381db
            warning: null
            width: 100
          -
            fieldUid: 7cce3872-9055-454a-8fdc-45cbccec785b # Left Stat Value
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd5488f4-d61b-42c0-aaeb-56645cc2db94
            warning: null
            width: 100
          -
            fieldUid: 4c127ec9-df18-4d62-bd02-cf8b5044f7ea # Left Stat Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 947ecc95-c90a-4075-9b4f-c0a21a97b069
            warning: null
            width: 100
          -
            fieldUid: 5f06df0c-02b7-4b2d-9b75-4b22a09c3a12 # Right Stat Value
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b3d17c8-4595-4726-8f68-622ff72515f7
            warning: null
            width: 100
          -
            fieldUid: 5ccbb75b-a9e9-455a-baf9-60aaa799d452 # Right Stat Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d41e49a-a8bb-404e-a36d-5a687a0bb8cb
            warning: null
            width: 100
          -
            fieldUid: 2b1996eb-1a60-4257-b4ab-2e41c49fbd06 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74bf588a-7119-4d19-b468-353cfb5a6691
            warning: null
            width: 100
        name: Content
        uid: 31b86478-b2de-4194-b7d1-91b6c0434033
fields:
  00f86307-b225-423b-bd34-b70af6632cf2: # Link Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkLabel
    instructions: null
    name: 'Link Label'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2b1996eb-1a60-4257-b4ab-2e41c49fbd06: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  4c127ec9-df18-4d62-bd02-cf8b5044f7ea: # Left Stat Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: leftStatLabel
    instructions: null
    name: 'Left Stat Label'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5ccbb75b-a9e9-455a-baf9-60aaa799d452: # Right Stat Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: rightStatLabel
    instructions: null
    name: 'Right Stat Label'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5f06df0c-02b7-4b2d-9b75-4b22a09c3a12: # Right Stat Value
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: rightStatValue
    instructions: null
    name: 'Right Stat Value'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7cce3872-9055-454a-8fdc-45cbccec785b: # Left Stat Value
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: leftStatValue
    instructions: null
    name: 'Left Stat Value'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  52ff2568-6318-44d5-a130-818c19f83360: # External Link
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: externalLink
    instructions: null
    name: 'External Link'
    searchable: true
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  d10684d5-bcd7-4e35-b0be-69377f981c39: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  eb7b8bc9-c07a-4a25-9201-8174bd70fcb9: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: VHC-no-assets.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  f466ab59-2e29-4cce-85b8-f9ebe7000b03: # Internal Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: internalLink
    instructions: 'Will override the External Link value if used.'
    name: 'Internal Link'
    searchable: true
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: statsAndImage
name: 'Stats and Image'
sortOrder: 3
