fieldLayouts:
  d9ce05a7-d7f7-4130-942e-6139d3f6b611:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 1b73d6e4-5373-4655-89da-9743f41255ec
            warning: null
            width: 100
        name: Content
        uid: 6fcf2489-8132-41b3-a21e-f5408389ccea
handle: demoTags
name: 'Demo Tags'
