fieldLayouts:
  d1f76894-056f-4ceb-be30-e908b48b3951:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 19d74c8a-102c-4dc1-97c6-437dc3d38073
            warning: null
            width: 100
          -
            fieldUid: 27881ad3-1379-497a-91a6-d495b2bbc7d1 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ff005bb-c63a-4881-b2fd-97ab53cdc2b5
            warning: null
            width: 100
          -
            fieldUid: beb1c87a-67bb-421f-933f-4bc3d1e125e3 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbb6f105-5ee0-43f5-a602-13cf82fde9d6
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb15a12d-1dec-435c-a55d-4054a10afeae
            warning: null
            width: 100
        name: Content
        uid: 92dad13e-da3d-481e-bcf9-511019079a8c
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 03c808f5-c39d-4cd5-9697-a4bcb442e1a6
            warning: null
            width: 100
          -
            fieldUid: 27881ad3-1379-497a-91a6-d495b2bbc7d1 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce0c3639-fa2a-437e-a1fb-92e5b3bc8124
            warning: null
            width: 100
          -
            fieldUid: beb1c87a-67bb-421f-933f-4bc3d1e125e3 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b51b8d2-68ab-4de7-a7ad-b55f8ff90058
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1a64811-2606-4f05-8d78-bb103af5d8c7
            warning: null
            width: 100
        name: Content
        uid: 4ff73355-e224-4c23-b443-3f77e6ea3358
handle: about
hasTitleField: false
name: About
section: 977f4737-eaaa-4d0f-aadb-10251ee1c4ff # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
