fieldLayouts:
  d1f76894-056f-4ceb-be30-e908b48b3951:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 034d7b5b-305a-41d3-b665-f418d5fe7d32
            warning: null
            width: 100
          -
            fieldUid: 27881ad3-1379-497a-91a6-d495b2bbc7d1 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b38ad04-1af6-4ee5-accd-617da486588e
            warning: null
            width: 100
          -
            fieldUid: beb1c87a-67bb-421f-933f-4bc3d1e125e3 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08b97938-9ed4-4230-9ca7-f9b16cd56fea
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61c0c60a-1c5e-47aa-ba37-4c9c85200299
            warning: null
            width: 100
        name: Content
        uid: 92dad13e-da3d-481e-bcf9-511019079a8c
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 00ffded3-b349-4f22-acac-047d54113f01
            warning: null
            width: 100
          -
            fieldUid: 27881ad3-1379-497a-91a6-d495b2bbc7d1 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48777d3e-c022-49b4-802a-735abb646c69
            warning: null
            width: 100
          -
            fieldUid: beb1c87a-67bb-421f-933f-4bc3d1e125e3 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78d8feee-abc8-476b-8aab-9b826422dc22
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a63d92c-2a68-41c9-8ee1-cb9a6c2835d4
            warning: null
            width: 100
        name: Content
        uid: 4ff73355-e224-4c23-b443-3f77e6ea3358
handle: about
hasTitleField: false
name: About
section: 977f4737-eaaa-4d0f-aadb-10251ee1c4ff # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
