fieldLayouts:
  d1f76894-056f-4ceb-be30-e908b48b3951:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5cb96b66-d232-428a-ac36-746009942d78
            warning: null
            width: 100
          -
            fieldUid: 27881ad3-1379-497a-91a6-d495b2bbc7d1 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eeb9c416-6ae6-4a5a-82fc-76544697ff8a
            warning: null
            width: 100
          -
            fieldUid: beb1c87a-67bb-421f-933f-4bc3d1e125e3 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd153353-d9fa-4a25-81a4-e160cf048788
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38c54aeb-5fd9-44e2-bb99-917094da076b
            warning: null
            width: 100
        name: Content
        uid: 92dad13e-da3d-481e-bcf9-511019079a8c
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3de16167-cefe-4b5d-93dd-a8f26e49adc9
            warning: null
            width: 100
          -
            fieldUid: 27881ad3-1379-497a-91a6-d495b2bbc7d1 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed84132f-7b0e-437c-aee8-405ceed07635
            warning: null
            width: 100
          -
            fieldUid: beb1c87a-67bb-421f-933f-4bc3d1e125e3 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09d232df-20f0-45b0-82f4-6499e12ef958
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 599712d1-19e2-4571-b134-fb34948f9a33
            warning: null
            width: 100
        name: Content
        uid: 4ff73355-e224-4c23-b443-3f77e6ea3358
handle: about
hasTitleField: false
name: About
section: 977f4737-eaaa-4d0f-aadb-10251ee1c4ff # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
