fieldLayouts:
  e1fad73a-2e23-4fa8-8f33-5037fe6b6d76:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7c29312c-bcc0-4433-892c-61b2c980ae24
            warning: null
            width: 100
          -
            fieldUid: cf7038b3-3aa7-4d1f-8a12-1cf0017d5b2c # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbe6c0aa-9902-4d17-9584-d67df02696a3
            warning: null
            width: 100
          -
            fieldUid: c3286b59-368a-4fdf-8dbe-48084247c9e2 # Featured Exhibits
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aff4b6ae-6a83-498e-8b85-96b92566d50d
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a39e2da-1049-4d51-a734-277d0f20dc37
            warning: null
            width: 100
        name: Content
        uid: 43dcd857-7ae7-401c-a897-4c85c08f5952
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 84132fe7-de8c-4c9f-96f7-abcc9126b096
            warning: null
            width: 100
          -
            fieldUid: cf7038b3-3aa7-4d1f-8a12-1cf0017d5b2c # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5c5e2cd-1e35-4af6-a8c3-7a50226b3941
            warning: null
            width: 100
          -
            fieldUid: c3286b59-368a-4fdf-8dbe-48084247c9e2 # Featured Exhibits
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5783d21c-91eb-4a3a-8a0c-5ffa8334388e
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74ea3556-7210-4686-8b62-7a1343f281c1
            warning: null
            width: 100
        name: Content
        uid: 84994a75-6482-4ca5-aade-5b4d2cfd878c
handle: home
hasTitleField: false
name: Home
section: 9d1ed50c-2239-4171-8b5a-ab121973301f # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
