fieldLayouts:
  f2d9b3bb-59ca-48fc-b355-3cb128ae9dd8:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 05a6fbf0-0baa-40f0-b7e8-18d836b03530
            warning: null
            width: 100
          -
            fieldUid: c3286b59-368a-4fdf-8dbe-48084247c9e2 # Featured Exhibits
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bb76992-dda0-4609-8cac-ca4ba7b651c6
            warning: null
            width: 100
          -
            fieldUid: 079ddf1a-d985-4de2-9929-8dc87fa2047f # News Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22eb9bb6-61dc-4aac-a0f2-1540a4859ee0
            warning: null
            width: 100
          -
            fieldUid: beb1c87a-67bb-421f-933f-4bc3d1e125e3 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65d56dde-ebf5-4dbd-9d76-5aed600b88d7
            warning: null
            width: 100
          -
            fieldUid: 59eb8fe2-8081-44bc-82ee-b7bc5f91c4ec # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1aef0c56-c8f3-4c15-ae08-4b33248f85b4
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3badabc9-7cbf-483d-b9c0-ecb3a2d533a5
            warning: null
            width: 100
        name: Content
        uid: cbd49574-dbbb-4022-bf6a-e0fd5fdf168d
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cd34c185-f3c5-4aec-86ea-60ec3908752f
            warning: null
            width: 100
          -
            fieldUid: c3286b59-368a-4fdf-8dbe-48084247c9e2 # Featured Exhibits
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f276bd38-e2e1-4413-8f2b-f27139e9d285
            warning: null
            width: 100
          -
            fieldUid: 079ddf1a-d985-4de2-9929-8dc87fa2047f # News Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89ab0e51-6ee9-4a99-ba2f-c0b137b7d187
            warning: null
            width: 100
          -
            fieldUid: beb1c87a-67bb-421f-933f-4bc3d1e125e3 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d6b63a3-7704-466c-96d9-4e2265ca69fd
            warning: null
            width: 100
          -
            fieldUid: 59eb8fe2-8081-44bc-82ee-b7bc5f91c4ec # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 134f4ac2-113f-4f7f-9c86-cc8f7e15de9d
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30629d7b-2181-48f7-bf69-c5924e3b92c1
            warning: null
            width: 100
        name: Content
        uid: 51600b4d-93ee-4ae9-ba59-ad0aca7ac509
handle: newsArticle
hasTitleField: true
name: 'News Article'
section: 666bcffb-61d7-43b4-a9f5-8c51c458b356 # News Articles
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
