fieldLayouts:
  624b2b8f-343a-4481-a172-20fe3cc8947d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5fa9d267-6209-433f-9b64-29df04c10064
            warning: null
            width: 100
          -
            fieldUid: a73bf239-f2f0-45ac-b84d-361e5dd1a75f # Pagination Count
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d76aa00f-c54b-40e1-839f-3858273aa91b
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54b625bc-3eb5-4e8e-b4d9-a9e689849dc3
            warning: null
            width: 100
        name: Content
        uid: 82eda493-e781-47e0-88e3-4c1d36844a66
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9e0f6d45-609a-427b-9009-45903ba57b58
            warning: null
            width: 100
          -
            fieldUid: a73bf239-f2f0-45ac-b84d-361e5dd1a75f # Pagination Count
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 512ca200-4ee6-458f-a3a0-f47573e2a202
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24168d33-75b0-467e-bfb1-382caaef9cb0
            warning: null
            width: 100
        name: Content
        uid: 049d260d-0f48-4750-bc49-0f44681cb7a9
handle: news
hasTitleField: false
name: News
section: 9b80c4d3-7a27-4bc4-af25-742e6cf5f77a # News
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
