fieldLayouts:
  f2d9b3bb-59ca-48fc-b355-3cb128ae9dd8:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f73cc2dc-36ca-4524-b978-1f7fdaba9121
            warning: null
            width: 100
          -
            fieldUid: c3286b59-368a-4fdf-8dbe-48084247c9e2 # Featured Exhibits
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ea93021-8812-44ff-99b2-fc73d7fa96b4
            warning: null
            width: 100
          -
            fieldUid: 079ddf1a-d985-4de2-9929-8dc87fa2047f # News Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e97f041-c6f8-49bf-baeb-2edc4131464f
            warning: null
            width: 100
          -
            fieldUid: beb1c87a-67bb-421f-933f-4bc3d1e125e3 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 898389c5-2f45-4cef-ac12-f85c9edf2cd5
            warning: null
            width: 100
          -
            fieldUid: 59eb8fe2-8081-44bc-82ee-b7bc5f91c4ec # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52c9dd0e-c87d-42c0-adf3-0e25e41ee46c
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb74a762-7d90-4c64-865b-cdd10b131650
            warning: null
            width: 100
        name: Content
        uid: cbd49574-dbbb-4022-bf6a-e0fd5fdf168d
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f836f03f-c7eb-47e8-92bd-e1d800b7597b
            warning: null
            width: 100
          -
            fieldUid: c3286b59-368a-4fdf-8dbe-48084247c9e2 # Featured Exhibits
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a1b7dcf-042c-4d0a-96fa-53f428a8a6b0
            warning: null
            width: 100
          -
            fieldUid: 079ddf1a-d985-4de2-9929-8dc87fa2047f # News Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5bcf05e-385d-47b1-ae70-04798ea2f61b
            warning: null
            width: 100
          -
            fieldUid: beb1c87a-67bb-421f-933f-4bc3d1e125e3 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ab0eeef-b452-4818-9b1e-263a6eeea0b8
            warning: null
            width: 100
          -
            fieldUid: 59eb8fe2-8081-44bc-82ee-b7bc5f91c4ec # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7cf93b27-8427-4194-b4c3-b492e0ad4e08
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 053d1a75-a206-43a3-838b-43cd1d57ba2e
            warning: null
            width: 100
        name: Content
        uid: 51600b4d-93ee-4ae9-ba59-ad0aca7ac509
handle: newsArticle
hasTitleField: true
name: 'News Article'
section: 666bcffb-61d7-43b4-a9f5-8c51c458b356 # News Articles
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
