fieldLayouts:
  624b2b8f-343a-4481-a172-20fe3cc8947d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b506bef0-4642-4a8a-8c76-0f3e69caad72
            warning: null
            width: 100
          -
            fieldUid: a73bf239-f2f0-45ac-b84d-361e5dd1a75f # Pagination Count
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3548d01-c025-4d2e-b553-00d320f1c9a4
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd9fd7e8-ea64-4a6d-80a3-31d61c16edc9
            warning: null
            width: 100
        name: Content
        uid: 82eda493-e781-47e0-88e3-4c1d36844a66
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 259c2887-eb07-4623-bd85-46e07e53eebf
            warning: null
            width: 100
          -
            fieldUid: a73bf239-f2f0-45ac-b84d-361e5dd1a75f # Pagination Count
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9cbe6f8e-7d9d-4e7d-81ea-1368b5c48d12
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97d3d54a-4947-4de4-b1ac-8c0c54965314
            warning: null
            width: 100
        name: Content
        uid: 049d260d-0f48-4750-bc49-0f44681cb7a9
handle: news
hasTitleField: false
name: News
section: 9b80c4d3-7a27-4bc4-af25-742e6cf5f77a # News
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
