fieldLayouts:
  73319165-f289-4758-a3f8-a617823df46f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c551bb45-d1b7-4771-b83b-3f09873964e2
            warning: null
            width: 100
          -
            fieldUid: 701ed750-1c7f-4b39-9be6-2c25746f29ba # Image Alt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2198fb68-6a27-4abb-8b41-caaac72a895d
            warning: null
            width: 100
          -
            fieldUid: 8b592bee-c976-4c83-be76-d749cc991410 # Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5076c968-98ab-49e8-babd-4f6aac52ea87
            warning: null
            width: 100
        name: Content
        uid: 64b711a5-b7a8-4dea-a6a9-4a8788e9a310
fs: images
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
