fieldLayouts:
  73319165-f289-4758-a3f8-a617823df46f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 1870920a-f914-44ad-84a9-4776221a20cb
            warning: null
            width: 100
          -
            fieldUid: 701ed750-1c7f-4b39-9be6-2c25746f29ba # Image Alt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 598c94f7-e776-4d48-9ff9-f1b651322382
            warning: null
            width: 100
          -
            fieldUid: 8b592bee-c976-4c83-be76-d749cc991410 # Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d49ce2f7-c5a1-462e-94c3-450511885b4e
            warning: null
            width: 100
        name: Content
        uid: 64b711a5-b7a8-4dea-a6a9-4a8788e9a310
fs: $FS_HANDLE
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
