fieldLayouts:
  eb1e53f5-82c8-40b9-9072-91da10f51fe7:
    tabs:
      -
        elements:
          -
            fieldUid: 1addbebe-4d59-4c1d-9607-6c47999665df # Links - Middle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6c30a81-8019-4056-bae6-eff3e62efa2e
            warning: null
            width: 100
          -
            fieldUid: 599f0646-f724-4ce4-a810-a8eaf7798b2d # Links - Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 856cf459-c3d2-44e7-9a00-bd2f8318076a
            warning: null
            width: 100
        name: 'Navigation Links'
        uid: f84cf6b3-3af0-4efa-8335-3d948640d582
handle: navigation
name: Navigation
sortOrder: 1
