name: Build and push docker images

on:
  workflow_call:
    inputs:
      dockerhub_push:
        default: ${{ github.event_name == 'release' }}
        required: true
        type: boolean
      dockerhub_username:
        default: ${{ secrets.DOCKERHUB_USERNAME }}
        required: true
        type: string
      dockerhub_password:
        default: ${{ secrets.DOCKERHUB_TOKEN }}
        required: true
        type: string
  push:
    branches:
      - staging
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push to Docker Hub
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ inputs.dockerhub_password }}

      - name: Build craftcms/demo-europa:staging
        if: ${{ github.ref == 'refs/heads/staging' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: craftcms/demo-europa:staging

      - name: Build craftcms/demo-europa:latest
        if: inputs.dockerhub_push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: craftcms/demo-europa:latest
