name: Build and push docker images

on:
  workflow_dispatch:
    inputs:
      dockerhub_push:
        default: false
        required: true
        type: boolean
  push:
    branches:
      - staging

  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push to Docker Hub
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build craftcms/demo-europa:staging
        if: ${{ github.event.inputs.dockerhub_push || github.ref == 'refs/heads/staging' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: craftcms/demo-europa:staging

      - name: Build craftcms/demo-europa:latest
        if: ${{ github.event.inputs.dockerhub_push || github.event_name == 'release' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: craftcms/demo-europa:latest
